// network

import Config from './config';

export const COLORS = {
  background: '#F8F8FA',
  surface: '#FFFFFF',
  badgeColor: '#edecf9',
  primary: '#111111',
  text: '#111111',
  textSecondary: '#6B6B6B',
  textMuted: '#8A8A8A',
  border: '#E7E7E7',
  borderStrong: '#D6D6D6',
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
};

export const FONTS = {
  regular: 'System',
  medium: 'System',
  semiBold: 'System',
  bold: 'System',
};

export const FONT_SIZES = {
  xs: 12,
  small: 14,
  body: 16,
  medium: 17,
  title: 20,
  heading: 28,
  largeHeading: 32,
};

export const SPACING = {
  xs: 4,
  small: 8,
  medium: 12,
  large: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  huge: 40,
};

export const RADIUS = {
  small: 8,
  medium: 12,
  large: 16,
  round: 999,
};

const CUSTOM_RPC_URL_ENV = Config.CUSTOM_RPC_URL;
const SEPOLIA_RPC_URL_ENV = Config.SEPOLIA_RPC_URL;
const CUSTOM_NETWORK_ENV = Config.CUSTOM_NETWORK;
const CUSTOM_NETWORK_CHAIN_ID_STR = Config.CUSTOM_NETWORK_CHAIN_ID;
const SEPOLIA_CHAIN_ID_STR = Config.SEPOLIA_CHAIN_ID;
const USDC_ADDRESS_ENV = Config.USDC_ADDRESS;
const BANK_ADDRESS_ENV = Config.BANK_ADDRESS;
const BRIDGE_ADDRESS_ENV = Config.BRIDGE_ADDRESS;
const EURC_ADDRESS_ENV = Config.EURC_ADDRESS;
const DENERGY_USDC_ADDRESS_ENV = Config.DENERGY_USDC_ADDRESS;
const DENERGY_EURC_ADDRESS_ENV = Config.DENERGY_EURC_ADDRESS;
const DESTINATION_ADDRESS_ENV = Config.DESTINATION_ADDRESS;
const STAKING_ADDRESS_ENV = Config.STAKING_ADDRESS;
const WATT_STAKING_ADDRESS_ENV = Config.WATT_STAKING_ADDRESS;
const STAKING_VALIDATOR_ADDRESS_ENV = Config.STAKING_VALIDATOR_ADDRESS;
const NFT_MARKET_ADDRESS_ENV = Config.NFT_MARKET_ADDRESS;
const API_NFT_URL_ENV = Config.API_NFT_URL;
const API_OFFSETTING_URL_ENV = Config.API_OFFSETTING_URL;
const GRAPH_API_NFTMARKET_ENV = Config.GRAPH_API_NFTMARKET;
const KYC_API_URL_ENV = Config.KYC_API_URL;
const KYC_API_KEY_ENV = Config.KYC_API_KEY;
const PLATFORM_SETTINGS_API_URL_ENV = Config.PLATFORM_SETTINGS_API_URL;
const PLATFORM_SETTINGS_API_KEY_ENV = Config.PLATFORM_SETTINGS_API_KEY;
const STAKED_API_URL_ENV = Config.STAKED_API_URL;
const NEWS_API_URL_ENV = Config.NEWS_API_URL;
const NEWS_API_KEY_ENV = Config.NEWS_API_KEY;
const ADDRESS_BOOK_API_URL_ENV = Config.ADDRESS_BOOK_API_URL;
const ADDRESS_BOOK_API_KEY_ENV = Config.ADDRESS_BOOK_API_KEY;
const NFT_DEFAULT_IMAGE_URL_ENV = Config.NFT_DEFAULT_IMAGE_URL;
const PRICE_HISTORY_API_URL_ENV = Config.PRICE_HISTORY_API_URL;
const VALIDATORS_API_URL_ENV = Config.VALIDATORS_API_URL;
const QUEUED_DELEGATIONS_API_URL_ENV = Config.QUEUED_DELEGATIONS_API_URL;
const WATT_QUEUED_DELEGATIONS_API_URL_ENV = Config.WATT_QUEUED_DELEGATIONS_API_URL;
const NFT_STAKED_ASSETS_API_URL_ENV = Config.NFT_STAKED_ASSETS_API_URL;
const WATT_STAKED_ASSETS_API_URL_ENV = Config.WATT_STAKED_ASSETS_API_URL;
const BRIDGE_API_URL_ENV = Config.BRIDGE_API_URL;
const BRIDGE_API_KEY_ENV = Config.BRIDGE_API_KEY;
const EXPLORER_URL_ENV = Config.EXPLORER_URL;
const CRYPTO_PRICES_API_URL_ENV = Config.CRYPTO_PRICES_API_URL;
const TREASURY_ADDRESS_ENV = Config.TREASURY_ADDRESS;
const MAGIC_API_KEY_PROD_ENV = Config.MAGIC_API_KEY_PROD;
const SWAP_SMART_ROUTER_ENV = Config.SWAP_SMART_ROUTER;
const SWAP_V3_QUOTER_ENV = Config.SWAP_V3_QUOTER;
const SWAP_V3_FACTORY_ENV = Config.SWAP_V3_FACTORY;
const SWAP_WETH_ENV = Config.SWAP_WETH;
const SEPOLIA_EXPLORER_URL_ENV = Config.SEPOLIA_EXPLORER_URL;
const MERGED_API_URL_ENV = Config.MERGED_API_URL;
const DEFAULT_GAS_LIMIT_ENV = Config.DEFAULT_GAS_LIMIT;
const API_TRANSFER_URL_ENV = Config.API_TRANSFER_URL;
const API_ACCOUNT_VALIDATE_URL_ENV = Config.API_ACCOUNT_VALIDATE_URL;
const WALLETCONNECT_PROJECT_ID_ENV = Config.WALLETCONNECT_PROJECT_ID;
export const CUSTOM_RPC_URL = CUSTOM_RPC_URL_ENV;
export const SEPOLIA_RPC_URL = SEPOLIA_RPC_URL_ENV;
export const CUSTOM_NETWORK = CUSTOM_NETWORK_ENV;
export const CUSTOM_NETWORK_CHAIN_ID = CUSTOM_NETWORK_CHAIN_ID_STR;
export const SEPOLIA_CHAIN_ID = SEPOLIA_CHAIN_ID_STR;
export const USDC_ADDRESS = USDC_ADDRESS_ENV;
export const BANK_ADDRESS = BANK_ADDRESS_ENV;
export const BRIDGE_ADDRESS = BRIDGE_ADDRESS_ENV;
export const EURC_ADDRESS = EURC_ADDRESS_ENV;
export const DENERGY_USDC_ADDRESS = DENERGY_USDC_ADDRESS_ENV;
export const DENERGY_EURC_ADDRESS = DENERGY_EURC_ADDRESS_ENV;
export const DESTINATION_ADDRESS = DESTINATION_ADDRESS_ENV;
export const STAKING_ADDRESS = STAKING_ADDRESS_ENV;
export const WATT_STAKING_ADDRESS = WATT_STAKING_ADDRESS_ENV;
export const STAKING_VALIDATOR_ADDRESS = STAKING_VALIDATOR_ADDRESS_ENV;
export const NFT_MARKET_ADDRESS = NFT_MARKET_ADDRESS_ENV;
export const API_NFT_URL = API_NFT_URL_ENV;
export const API_OFFSETTING_URL = API_OFFSETTING_URL_ENV;
export const GRAPH_API_NFTMARKET = GRAPH_API_NFTMARKET_ENV;
export const KYC_API_URL = KYC_API_URL_ENV;
export const KYC_API_KEY = KYC_API_KEY_ENV;
export const PLATFORM_SETTINGS_API_URL = PLATFORM_SETTINGS_API_URL_ENV;
export const PLATFORM_SETTINGS_API_KEY = PLATFORM_SETTINGS_API_KEY_ENV;
export const STAKED_API_URL = STAKED_API_URL_ENV;
export const NEWS_API_URL = NEWS_API_URL_ENV;
export const NEWS_API_KEY = NEWS_API_KEY_ENV;
export const ADDRESS_BOOK_API_URL = ADDRESS_BOOK_API_URL_ENV;
export const ADDRESS_BOOK_API_KEY = ADDRESS_BOOK_API_KEY_ENV;
export const NFT_DEFAULT_IMAGE_URL = NFT_DEFAULT_IMAGE_URL_ENV;
export const PRICE_HISTORY_API_URL = PRICE_HISTORY_API_URL_ENV;
export const VALIDATORS_API_URL = VALIDATORS_API_URL_ENV;
export const QUEUED_DELEGATIONS_API_URL = QUEUED_DELEGATIONS_API_URL_ENV;
export const WATT_QUEUED_DELEGATIONS_API_URL =
  WATT_QUEUED_DELEGATIONS_API_URL_ENV;
export const NFT_STAKED_ASSETS_API_URL = NFT_STAKED_ASSETS_API_URL_ENV;
export const WATT_STAKED_ASSETS_API_URL = WATT_STAKED_ASSETS_API_URL_ENV;
export const BRIDGE_API_URL = BRIDGE_API_URL_ENV;
export const BRIDGE_API_KEY = BRIDGE_API_KEY_ENV;
export const EXPLORER_URL = EXPLORER_URL_ENV;
export const CRYPTO_PRICES_API_URL = CRYPTO_PRICES_API_URL_ENV;
export const TREASURY_ADDRESS = TREASURY_ADDRESS_ENV;
export const MAGIC_API_KEY_PROD = MAGIC_API_KEY_PROD_ENV;
export const SWAP_SMART_ROUTER = SWAP_SMART_ROUTER_ENV;
export const SWAP_V3_QUOTER = SWAP_V3_QUOTER_ENV;
export const SWAP_V3_FACTORY = SWAP_V3_FACTORY_ENV;
export const SWAP_WETH = SWAP_WETH_ENV;
export const SEPOLIA_EXPLORER_URL = SEPOLIA_EXPLORER_URL_ENV;
export const MERGED_API_URL = MERGED_API_URL_ENV;
export const DEFAULT_GAS_LIMIT = DEFAULT_GAS_LIMIT_ENV;
export const API_TRANSFER_URL = API_TRANSFER_URL_ENV;
export const API_ACCOUNT_VALIDATE_URL = API_ACCOUNT_VALIDATE_URL_ENV;
export const TOKEN_CONTRACTS = {
  denergy: {
    USDC: DENERGY_USDC_ADDRESS_ENV,
    EURC: DENERGY_EURC_ADDRESS_ENV,
  },
  sepolia: {
    USDC: USDC_ADDRESS_ENV,
    EURC: EURC_ADDRESS_ENV,
  },
  nftMarket: NFT_MARKET_ADDRESS,
};

// WalletConnect Configuration
export const WALLETCONNECT_PROJECT_ID = WALLETCONNECT_PROJECT_ID_ENV;

// WalletConnect supported chains in CAIP-2 format
export const WALLETCONNECT_CHAINS = {
  denergy: `eip155:${CUSTOM_NETWORK_CHAIN_ID}`,
  sepolia: `eip155:${SEPOLIA_CHAIN_ID}`,
};

export const SERVICE_CATEGORIES = [
  'Hair',
  'Hair Color',
  'Hair Spa',
  'Facial',
  'Cleanup',
  'Bleach',
  'Threading',
  'Waxing',
  'Makeup',
  'Bridal',
  'Nails',
  'Massage',
  'Skin',
  'Beard',
  'Shaving',
  'Kids',
  'Other',
];