export const appointments = [
  {
    id: '1',
    customer: 'Ananya',
    service: 'Haircut + Hair Spa',
    staff: 'Riya',
    amount: 1200,
    time: '10:00 AM',
    status: 'CONFIRMED',
    phone: '9876543210',
  },
  {
    id: '2',
    customer: 'Rahul',
    service: 'Beard Styling',
    staff: 'John',
    amount: 500,
    time: '11:30 AM',
    status: 'IN_PROGRESS',
    phone: '9876543211',
  },
  {
    id: '3',
    customer: 'Sneha',
    service: 'Bridal Makeup',
    staff: 'Priya',
    amount: 8500,
    time: '2:00 PM',
    status: 'COMPLETED',
    phone: '9876543212',
  },
  {
    id: '4',
    customer: 'Rohit',
    service: 'Hair Coloring',
    staff: 'Amit',
    amount: 3000,
    time: '4:30 PM',
    status: 'CANCELLED',
    phone: '9876543213',
  },
];