export default {
  backHeaderArrow: require('../assets/images/Arrowback.png'),
  logoBlueNew: require('../assets/images/logo-blue_new.png'),
  email: require('../assets/images/email.png'),
  home: require('../assets/images/home.png'),
  wallet: require('../assets/images/wallet.png'),
  shop: require('../assets/images/shop.png'),
  category: require('../assets/images/category.png'),
  stake: require('../assets/images/stake.png'),
  homeActive: require('../assets/images/home-active.png'),
  walletActive: require('../assets/images/wallet-active.png'),
  shopActive: require('../assets/images/shop-active.png'),
  categoryActive: require('../assets/images/category-active.png'),
  stakeActive: require('../assets/images/stake-active.png'),
  //
  onboard1: require('../assets/images/onboard-1.png'),
  onboard2: require('../assets/images/onboard-2.png'),
  onboard3: require('../assets/images/onboard-3.png'),
  onboard4: require('../assets/images/onboard-4.png'),
  forward: require('../assets/images/forward.png'),
  notification: require('../assets/images/notification.png'),
  profile: require('../assets/images/profile.png'),
  verified: require('../assets/images/verified-symbol-icon.png'),
  newstemp1: require('../assets/images/newtemp1.jpeg'),
  newstemp2: require('../assets/images/newstemp2.jpeg'),
  newstemp3: require('../assets/images/newstemp3.jpeg'),
  next: require('../assets/images/next.png'),
  watt: require('../assets/images/watt.png'),
  bitcoin: require('../assets/images/bitcoin.png'),
  usdt: require('../assets/images/usdt.png'),
  usdc: require('../assets/images/usdc.png'),
  euroc: require('../assets/images/euroc.png'),
  ethereum: require('../assets/images/ethereum.png'),
  sharePriceIcon: require('../assets/images/marketIcon.png'),
};
