import { StyleSheet } from 'react-native';
import { fontsFamily } from '../../Theme';
export default StyleSheet.create({
  container: {
    marginLeft: 21,
    marginRight: 21,
  },
  font: {
    fontFamily: fontsFamily.MulishBold,
    fontSize: 18,
    color: '#1F1F1F',
    lineHeight: 22,
    marginHorizontal: 18,
    marginTop: 36,
    marginBottom: 20,
  },
  portfolioMainView: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 15,
  },
  priceContentView: {
    flexDirection: 'row',
    marginTop: -20,
    alignItems: 'center',
  },
  sharePriceIcon: {
    width: 20,
    height: 20,
    marginHorizontal: 5,
  },
  myCryptosContainer: {
    marginTop: 20,
    // marginBottom: 30,
  },
  content: {
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    color: '#00201B',
    // lineHeight:20,
    letterSpacing: 1.5,
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  contentText: {
    fontFamily: fontsFamily.MulishExtraBold,
    fontSize: 28,
    color: '#000',
  },
  pricetext: {
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    color: '#000',
    // lineHeight:40,
    // letterSpacing:1
  },
  priceFont: {
    fontFamily: fontsFamily.MulishBold,
    fontSize: 12,
    color: '#8F8F8F',
  },
  HeaderFont: {
    fontFamily: fontsFamily.MulishBold,
    color: '#000',
    fontSize: 12,
    lineHeight: 20,
    letterSpacing: 1.5,
    marginBottom: 15,
    marginLeft: 20,
  },
  divider: {
    borderColor: '#E8E8E8',
    borderWidth: 0.5,
    width: '100%',
    marginVertical: 10,
  },
  coinName: {
    fontFamily: fontsFamily.MulishBold,
    fontSize: 14,
    lineHeight: 16,
    color: '#515151',
    marginVertical: 4,
  },
  coinCode: {
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    lineHeight: 16,
    color: '#A6A6A6',
  },
  amount: {
    fontFamily: fontsFamily.MulishExtraBold,
    fontSize: 14,
    lineHeight: 16,
    color: '#515151',
  },
  valueFont: {
    color: '#0FB990',
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 10,
    lineHeight: 16,
  },
  header: {
    fontFamily: fontsFamily.MulishBold,
    fontSize: 14,
    lineHeight: 22,
    color: '#000',
  },
  usdvalue: {
    color: '#000',
    fontSize: 12,
    marginLeft: 25,
    fontFamily: fontsFamily.MulishBold,
  },
  Today: {
    marginBottom: 1,
    marginLeft: 25,
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    lineHeight: 16,
    color: '#A6A6A6',
  },
  buttonContainer: {
    width: '45%',
    borderColor: '#000',
    borderWidth: 1.2,
    padding: 12,
    borderRadius: 7,
  },
  divider: {
    borderColor: '#E8E8E8',
    borderWidth: 0.5,
    width: '100%',
    marginVertical: 10,
  },
  contentText: {
    fontFamily: fontsFamily.MulishExtraBold,
    fontSize: 25,
    color: '#000',
    lineHeight: 40,
    letterSpacing: 1,
  },
  buttonLabelStyle: {
    fontSize: 14,
    textAlign: 'center',
    fontFamily: fontsFamily.MulishBold,
    color: '#000',
  },
  LoginbuttonLabelStyle: {
    fontSize: 14,
    textAlign: 'center',
    fontFamily: fontsFamily.MulishBold,
    color: '#ffff',
  },
  recivepagewattid: {
    fontFamily: fontsFamily.MulishExtraBold,
    fontSize: 14,
    // lineHeight:16,
    color: '#515151',
    // marginVertical:4
  },
  listContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopColor: '#E8E8E8',
    borderTopWidth: 1,
    width: '100%',
    paddingVertical: 20,
  },
  listView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  valueBox: {
    padding: 4,
    paddingLeft: 8,
    backgroundColor: '#E4FFFD',
    borderRadius: 4,
    marginHorizontal: 10,
  },
  value: {
    color: '#009D94',
    fontSize: 12,
    fontFamily: fontsFamily.MulishSemiBold,
  },
  arrowStyle: {
    width: 20,
    height: 20,
    transform: [{rotate: '180deg'}],
  },
  dividerCoins: {
    borderTopColor: '#E8E8E8',
    borderTopWidth: 1,
    alignSelf: 'center',
    width: '100%',
  },
});
