// network

import {
  CUSTOM_RPC_URL as CUSTOM_RPC_URL_ENV,
  SEPOLIA_RPC_URL as SEPOLIA_RPC_URL_ENV,
  CUSTOM_NETWORK as CUSTOM_NETWORK_ENV,
  CUSTOM_NETWORK_CHAIN_ID as CUSTOM_NETWORK_CHAIN_ID_STR,
  SEPOLIA_CHAIN_ID as SEPOLIA_CHAIN_ID_STR,
  USDC_ADDRESS as USDC_ADDRESS_ENV,
  BANK_ADDRESS as BANK_ADDRESS_ENV,
  BRIDGE_ADDRESS as BRIDGE_ADDRESS_ENV,
  EURC_ADDRESS as EURC_ADDRESS_ENV,
  DENERGY_USDC_ADDRESS as DENERGY_USDC_ADDRESS_ENV,
  DENERGY_EURC_ADDRESS as DENERGY_EURC_ADDRESS_ENV,
  DESTINATION_ADDRESS as DESTINATION_ADDRESS_ENV,
  STAKING_ADDRESS as STAKING_ADDRESS_ENV,
  WATT_STAKING_ADDRESS as WATT_STAKING_ADDRESS_ENV,
  STAKING_VALIDATOR_ADDRESS as STAKING_VALIDATOR_ADDRESS_ENV,
  NFT_MARKET_ADDRESS as NFT_MARKET_ADDRESS_ENV,
  API_NFT_URL as API_NFT_URL_ENV,
  API_OFFSETTING_URL as API_OFFSETTING_URL_ENV,
  GRAPH_API_NFTMARKET as GRAPH_API_NFTMARKET_ENV,
  KYC_API_URL as KYC_API_URL_ENV,
  KYC_API_KEY as KYC_API_KEY_ENV,
  PLATFORM_SETTINGS_API_URL as PLATFORM_SETTINGS_API_URL_ENV,
  PLATFORM_SETTINGS_API_KEY as PLATFORM_SETTINGS_API_KEY_ENV,
  STAKED_API_URL as STAKED_API_URL_ENV,
  NEWS_API_URL as NEWS_API_URL_ENV,
  NEWS_API_KEY as NEWS_API_KEY_ENV,
  ADDRESS_BOOK_API_URL as ADDRESS_BOOK_API_URL_ENV,
  ADDRESS_BOOK_API_KEY as ADDRESS_BOOK_API_KEY_ENV,
  NFT_DEFAULT_IMAGE_URL as NFT_DEFAULT_IMAGE_URL_ENV,
  PRICE_HISTORY_API_URL as PRICE_HISTORY_API_URL_ENV,
  VALIDATORS_API_URL as VALIDATORS_API_URL_ENV,
  BRIDGE_API_URL as BRIDGE_API_URL_ENV,
  BRIDGE_API_KEY as BRIDGE_API_KEY_ENV,
  EXPLORER_URL as EXPLORER_URL_ENV,
  CRYPTO_PRICES_API_URL as CRYPTO_PRICES_API_URL_ENV,
  TREASURY_ADDRESS as TREASURY_ADDRESS_ENV,
  MAGIC_API_KEY_PROD as MAGIC_API_KEY_PROD_ENV,
  SWAP_SMART_ROUTER as SWAP_SMART_ROUTER_ENV,
  SWAP_V3_QUOTER as SWAP_V3_QUOTER_ENV,
  SWAP_V3_FACTORY as SWAP_V3_FACTORY_ENV,
  SWAP_WETH as SWAP_WETH_ENV,
  SEPOLIA_EXPLORER_URL as SEPOLIA_EXPLORER_URL_ENV,
  MERGED_API_URL as MERGED_API_URL_ENV,
  DEFAULT_GAS_LIMIT as DEFAULT_GAS_LIMIT_ENV,
} from '@env';

console.log('API_URL2', {
  CUSTOM_RPC_URL_ENV,
  SEPOLIA_RPC_URL_ENV,
  CUSTOM_NETWORK_ENV,
  CUSTOM_NETWORK_CHAIN_ID_STR,
  SEPOLIA_CHAIN_ID_STR,
  USDC_ADDRESS_ENV,
  BANK_ADDRESS_ENV,
  BRIDGE_ADDRESS_ENV,
  EURC_ADDRESS_ENV,
  DENERGY_USDC_ADDRESS_ENV,
  DENERGY_EURC_ADDRESS_ENV,
  DESTINATION_ADDRESS_ENV,
  STAKING_ADDRESS_ENV,
  STAKING_VALIDATOR_ADDRESS_ENV,
  NFT_MARKET_ADDRESS_ENV,
  API_NFT_URL_ENV,
  API_OFFSETTING_URL_ENV,
  GRAPH_API_NFTMARKET_ENV,
  KYC_API_URL_ENV,
  KYC_API_KEY_ENV,
  PLATFORM_SETTINGS_API_URL_ENV,
  PLATFORM_SETTINGS_API_KEY_ENV,
  STAKED_API_URL_ENV,
  NEWS_API_URL_ENV,
  NEWS_API_KEY_ENV,
  ADDRESS_BOOK_API_URL_ENV,
  ADDRESS_BOOK_API_KEY_ENV,
  NFT_DEFAULT_IMAGE_URL_ENV,
  PRICE_HISTORY_API_URL_ENV,
  BRIDGE_API_URL_ENV,
  BRIDGE_API_KEY_ENV,
  EXPLORER_URL_ENV,
  CRYPTO_PRICES_API_URL_ENV,
  TREASURY_ADDRESS_ENV,
});

export const CUSTOM_RPC_URL = CUSTOM_RPC_URL_ENV;
export const SEPOLIA_RPC_URL = SEPOLIA_RPC_URL_ENV;
export const CUSTOM_NETWORK = CUSTOM_NETWORK_ENV;
export const CUSTOM_NETWORK_CHAIN_ID = CUSTOM_NETWORK_CHAIN_ID_STR;
export const SEPOLIA_CHAIN_ID = SEPOLIA_CHAIN_ID_STR;

export const USDC_ADDRESS = USDC_ADDRESS_ENV;
export const BANK_ADDRESS = BANK_ADDRESS_ENV;
export const BRIDGE_ADDRESS = BRIDGE_ADDRESS_ENV;
export const EURC_ADDRESS = EURC_ADDRESS_ENV;
export const DENERGY_USDC_ADDRESS = DENERGY_USDC_ADDRESS_ENV;
export const DENERGY_EURC_ADDRESS = DENERGY_EURC_ADDRESS_ENV;
export const DESTINATION_ADDRESS = DESTINATION_ADDRESS_ENV;
export const STAKING_ADDRESS = STAKING_ADDRESS_ENV;
export const WATT_STAKING_ADDRESS = WATT_STAKING_ADDRESS_ENV;
export const STAKING_VALIDATOR_ADDRESS = STAKING_VALIDATOR_ADDRESS_ENV;
export const NFT_MARKET_ADDRESS = NFT_MARKET_ADDRESS_ENV;

export const API_NFT_URL = API_NFT_URL_ENV;
export const API_OFFSETTING_URL = API_OFFSETTING_URL_ENV;
export const GRAPH_API_NFTMARKET = GRAPH_API_NFTMARKET_ENV;
export const KYC_API_URL = KYC_API_URL_ENV;
export const KYC_API_KEY = KYC_API_KEY_ENV;
export const PLATFORM_SETTINGS_API_URL = PLATFORM_SETTINGS_API_URL_ENV;
export const PLATFORM_SETTINGS_API_KEY = PLATFORM_SETTINGS_API_KEY_ENV;
export const STAKED_API_URL = STAKED_API_URL_ENV;
export const NEWS_API_URL = NEWS_API_URL_ENV;
export const NEWS_API_KEY = NEWS_API_KEY_ENV;
export const ADDRESS_BOOK_API_URL = ADDRESS_BOOK_API_URL_ENV;
export const ADDRESS_BOOK_API_KEY = ADDRESS_BOOK_API_KEY_ENV;
export const NFT_DEFAULT_IMAGE_URL = NFT_DEFAULT_IMAGE_URL_ENV;
export const PRICE_HISTORY_API_URL = PRICE_HISTORY_API_URL_ENV;
export const VALIDATORS_API_URL = VALIDATORS_API_URL_ENV;
export const BRIDGE_API_URL = BRIDGE_API_URL_ENV;
export const BRIDGE_API_KEY = BRIDGE_API_KEY_ENV;
export const EXPLORER_URL = EXPLORER_URL_ENV;
export const CRYPTO_PRICES_API_URL = CRYPTO_PRICES_API_URL_ENV;
export const TREASURY_ADDRESS = TREASURY_ADDRESS_ENV;
export const MAGIC_API_KEY_PROD = MAGIC_API_KEY_PROD_ENV;
export const SWAP_SMART_ROUTER = SWAP_SMART_ROUTER_ENV;
export const SWAP_V3_QUOTER = SWAP_V3_QUOTER_ENV;
export const SWAP_V3_FACTORY = SWAP_V3_FACTORY_ENV;
export const SWAP_WETH = SWAP_WETH_ENV;
export const SEPOLIA_EXPLORER_URL = SEPOLIA_EXPLORER_URL_ENV;
export const MERGED_API_URL = MERGED_API_URL_ENV;
export const DEFAULT_GAS_LIMIT = DEFAULT_GAS_LIMIT_ENV;

export const TOKEN_CONTRACTS = {
  denergy: {
    USDC: DENERGY_USDC_ADDRESS_ENV,
    EURC: DENERGY_EURC_ADDRESS_ENV,
  },
  sepolia: {
    USDC: USDC_ADDRESS_ENV,
    EURC: EURC_ADDRESS_ENV,
  },
  nftMarket: NFT_MARKET_ADDRESS,
};
