import {StyleSheet} from 'react-native';
import {Colors, fontsFamily} from '../../../Theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  backContainer: {
    position: 'relative',
  },
  nameContainer: {
    flexDirection: 'row',
  },
  title: {
    fontSize: 20,
    lineHeight: 25,
    color: '#000',
  },
  headerContainer: {
    borderBottomWidth: 0,
  },
  scrollViewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 21,
    marginTop: 20,
  },
  addressInputWrap: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#d3d3d3',
    borderRadius: 10,
    height: 52,
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 85,
    width: '100%',
    position: 'relative',
    justifyContent: 'flex-start',
    alignSelf: 'stretch',
  },
  addressInput: {
    color: '#000000',
    flex: 1,
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    paddingHorizontal: 10,
    height: 52,
    textAlignVertical: 'center',
    includeFontPadding: false,
    paddingVertical: 0,
    margin: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    multiline: false,
    numberOfLines: 1,
  },
  bottomButton: {
    height: 51,
    borderRadius: 12,
    marginBottom: 40,
    marginHorizontal: 10,
  },
  buttonImage: {
    height: 51,
    width: '100%',
  },
  textStyle: {
    fontSize: 16,
    color: '#fff',
  },
  iconsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    right: 8,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    height: 52,
    pointerEvents: 'box-none',
  },
  iconButton: {
    padding: 8,
    marginLeft: 0,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 32,
    minWidth: 32,
    position: 'static',
  },
  iconStyle: {
    height: 18,
    width: 18,
    tintColor: '#009D94',
  },
  contactIconText: {
    fontSize: 18,
    color: '#009D94',
  },
  selectedAddressContainer: {
    backgroundColor: '#f8f9fa',
    marginHorizontal: 21,
    marginTop: 12,
    padding: 15,
    borderRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#009D94',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  selectedAddressLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 6,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  selectedAddressText: {
    fontSize: 14,
    color: '#333',
    fontFamily: 'monospace',
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    lineHeight: 20,
  },
});
