import {StyleSheet} from 'react-native';
import {Colors, fontsFamily} from '../../../Theme';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  font: {
    fontFamily: fontsFamily.MulishBold,
    fontSize: 18,
    color: '#1F1F1F',
    lineHeight: 22,
  },
  content: {
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    color: '#747474',
    lineHeight: 20,
    letterSpacing: 1,
  },
  contentText: {
    fontFamily: fontsFamily.MulishExtraBold,
    fontSize: 24,
    color: '#000',
    lineHeight: 40,
    letterSpacing: 1,
    marginTop: 35,
  },
  pricetext: {
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    color: '#000',
    // lineHeight:40,
    // letterSpacing:1
  },
  priceFont: {
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    color: '#8F8F8F',
  },
  HeaderFont: {
    fontFamily: fontsFamily.MulishBold,
    color: '#000',
    fontSize: 12,
    lineHeight: 20,
    letterSpacing: 1,
  },
  divider: {
    borderColor: '#E8E8E8',
    borderWidth: 0.5,
    width: '100%',
    marginVertical: 10,
  },
  coinName: {
    fontFamily: fontsFamily.MulishExtraBold,
    fontSize: 13,
    lineHeight: 16,
    color: '#515151',
    marginVertical: 4,
  },
  coinCode: {
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    lineHeight: 16,
    color: '#A6A6A6',
  },
  valueFont: {
    color: '#0FB990',
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 12,
    lineHeight: 16,
  },
  header: {
    fontFamily: fontsFamily.MulishBold,
    fontSize: 14,
    lineHeight: 22,
    color: '#000',
  },
  card: {
    backgroundColor: '#ffffff',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: 24,
    borderTopLeftRadius: 24,
  },
  cardTitle: {
    color: '#333333',
    fontFamily: fontsFamily.MulishSemiBold,
    fontSize: 18,
    marginTop: 20,
    textAlign: 'center',
  },
  cardSubText: {
    width: '62%',
    marginTop: 12,
    fontFamily: fontsFamily.Mulish,
    fontSize: 14,
    color: '#747474',
    textAlign: 'center',
  },
  starContainer: {
    width: '62%',
    marginBottom: 15,
  },
  rateImgStyle: {
    marginTop: 20,
    alignSelf: 'center',
    width: 50,
    height: 50,
  },
  rateTextStyle: {
    fontFamily: fontsFamily.MulishSemiBold,
    color: '#000000',
    textAlign: 'center',
    fontSize: 16,
    marginTop: 30,
    marginBottom: -10,
  },
});
