const Config = {
  CUSTOM_RPC_URL: '',
  SEPOLIA_RPC_URL: '',
  CUSTOM_NETWORK: '',
  CUSTOM_NETWORK_CHAIN_ID: '',
  SEPOLIA_CHAIN_ID: '',

  USDC_ADDRESS: '',
  BANK_ADDRESS: '',
  BRIDGE_ADDRESS: '',
  EURC_ADDRESS: '',
  DENERGY_USDC_ADDRESS: '',
  DENERGY_EURC_ADDRESS: '',
  DESTINATION_ADDRESS: '',
  STAKING_ADDRESS: '',
  WATT_STAKING_ADDRESS: '',
  STAKING_VALIDATOR_ADDRESS: '',
  NFT_MARKET_ADDRESS: '',

  API_NFT_URL: '',
  API_OFFSETTING_URL: '',
  GRAPH_API_NFTMARKET: '',
  KYC_API_URL: '',
  KYC_API_KEY: '',

  PLATFORM_SETTINGS_API_URL: '',
  PLATFORM_SETTINGS_API_KEY: '',
  STAKED_API_URL: '',
  NEWS_API_URL: '',
  NEWS_API_KEY: '',

  ADDRESS_BOOK_API_URL: '',
  ADDRESS_BOOK_API_KEY: '',
  NFT_DEFAULT_IMAGE_URL: '',
  PRICE_HISTORY_API_URL: '',
  VALIDATORS_API_URL: '',

  QUEUED_DELEGATIONS_API_URL: '',
  WATT_QUEUED_DELEGATIONS_API_URL: '',
  NFT_STAKED_ASSETS_API_URL: '',
  WATT_STAKED_ASSETS_API_URL: '',

  BRIDGE_API_URL: '',
  BRIDGE_API_KEY: '',
  EXPLORER_URL: '',
  CRYPTO_PRICES_API_URL: '',
  TREASURY_ADDRESS: '',

  MAGIC_API_KEY_PROD: '',

  SWAP_SMART_ROUTER: '',
  SWAP_V3_QUOTER: '',
  SWAP_V3_FACTORY: '',
  SWAP_WETH: '',

  SEPOLIA_EXPLORER_URL: '',
  MERGED_API_URL: '',

  DEFAULT_GAS_LIMIT: '',
  API_TRANSFER_URL: '',
  API_ACCOUNT_VALIDATE_URL: '',

  WALLETCONNECT_PROJECT_ID: '',
};

export default Config;